FROM daocloud.io/ubuntu:18.04 as builder


# 更改源

RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list

# 千万不能加sudo,一定要加  -y
RUN  apt update &&  apt -y  install gcc make git

WORKDIR /data
RUN git clone  https://github.com/beanstalkd/beanstalkd.git
WORKDIR /data/beanstalkd
RUN make && ls -la
FROM daocloud.io/ubuntu:18.04
RUN  adduser beanstalkd
RUN mkdir /data && chown beanstalkd:beanstalkd /data
VOLUME /data
WORKDIR /data
COPY docker-entrypoint.sh /usr/local/bin/
COPY --from=builder /data/beanstalkd/beanstalkd /usr/local/bin/
ENV PATH ${PATH}:/usr/local/bin/
USER beanstalkd
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 11300
CMD ["beanstalkd"]

# sudo docker run --restart=always  -d --name beanstalk -p 11300:11300 beanstalkd:v1